
platform :ios, '8.0'

use_frameworks!

#pod 'SnapKit'
#pod 'RxSwift',    '~> 2.0'
#pod 'RxCocoa',    '~> 2.0'
pod 'JSPatch'
pod 'Aspects'
pod 'AsyncDisplayKit'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'FMDB'
pod 'BlocksKit'
pod 'MagicalRecord'
pod 'YYKit'
pod 'MBProgressHUD'
pod 'ReactiveCocoa',    '2.5'
pod 'Mantle'
pod 'PLCrashReporter'
pod 'CRToast'
#pod 'MLeaksFinder'
